name: Node.js Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for "main" and "dev" branch
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#jobs that will be ran on every PR or push
jobs:
#job 1 - automatically set reviewers
  auto_set_reviewers: 
    name: Auto Set Reviewers
    runs-on: ubuntu-latest
    
    steps: 
      - name: Step 1 - checkout repository
        uses: actions/checkout@v2
      
      - name: Step 2 - Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18
          
      - name: Step 3 - Run package-lock json replication
        run: npm ci
        
      - name: Step 4 - Set reviewers
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.repository }}"
          
          curl \
            -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER/requested_reviewers" \
            -d '{
              "reviewers": ["mbildstein", "wnguye03", "li-lucia", "davidan1989", "YouruiR"]
            }'
        
      
      
#job 2 - build
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Run package-lock json replication
        run: npm ci
        
      - name: Step 2 - Run npm build 
        run: npm run build --if-present
        
      - name: Step 3 - Run test
        run: npm test --if-present
